---
- hosts: all

  become: true

  tasks:
    - name: Execute ls command
      command: ls
      register: ls_output

    - name: Display ls output
      debug:
        var: ls_output.stdout_lines
